const items = [

/* ================= ORES ================= */

{name:"64x Stone",price:2,category:"Ores"},
{name:"64x Cobblestone",price:2,category:"Ores"},
{name:"64x Coal",price:3,category:"Ores"},
{name:"64x Iron Ingot",price:5,category:"Ores"},
{name:"64x Copper Ingot",price:4,category:"Ores"},
{name:"64x Gold Ingot",price:5,category:"Ores"},
{name:"64x Redstone",price:4,category:"Ores"},
{name:"64x Lapis Lazuli",price:4,category:"Ores"},
{name:"64x Diamond",price:7,category:"Ores"},
{name:"64x Emerald",price:7,category:"Ores"},
{name:"64x Netherite Ingot",price:10,category:"Ores"},
{name:"64x Quartz",price:4,category:"Ores"},
{name:"64x Amethyst Shard",price:5,category:"Ores"},

/* ================= WOODS ================= */

{name:"Oak Log",price:2,category:"Woods"},
{name:"Birch Log",price:2,category:"Woods"},
{name:"Spruce Log",price:2,category:"Woods"},
{name:"Jungle Log",price:2,category:"Woods"},
{name:"Acacia Log",price:2,category:"Woods"},
{name:"Dark Oak Log",price:2,category:"Woods"},
{name:"Mangrove Log",price:3,category:"Woods"},
{name:"Cherry Log",price:3,category:"Woods"},
{name:"Bamboo Block",price:3,category:"Woods"},

/* ================= BLOCKS ================= */

{name:"64x Dirt",price:1,category:"Blocks"},
{name:"64x Grass Block",price:2,category:"Blocks"},
{name:"64x Stone",price:2,category:"Blocks"},
{name:"64x Cobblestone",price:2,category:"Blocks"},
{name:"64x Deepslate",price:2,category:"Blocks"},
{name:"64x Sand",price:2,category:"Blocks"},
{name:"64x Red Sand",price:2,category:"Blocks"},
{name:"64x Gravel",price:2,category:"Blocks"},
{name:"64x Glass",price:2,category:"Blocks"},
{name:"64x Glass Pane",price:2,category:"Blocks"},
{name:"64x Obsidian",price:4,category:"Blocks"},
{name:"64x Crying Obsidian",price:5,category:"Blocks"},
{name:"64x Bedrock",price:10,category:"Blocks"},
{name:"64x Bricks",price:2,category:"Blocks"},
{name:"64x Stone Bricks",price:2,category:"Blocks"},
{name:"64x Mossy Stone Bricks",price:3,category:"Blocks"},
{name:"64x Cracked Stone Bricks",price:3,category:"Blocks"},
{name:"64x Chiseled Stone Bricks",price:3,category:"Blocks"},
{name:"64x Smooth Stone",price:2,category:"Blocks"},
{name:"64x Smooth Quartz",price:3,category:"Blocks"},
{name:"64x Quartz Block",price:3,category:"Blocks"},
{name:"64x Quartz Pillar",price:3,category:"Blocks"},
{name:"64x Glowstone",price:3,category:"Blocks"},
{name:"64x Sea Lantern",price:4,category:"Blocks"},
{name:"64x Prismarine",price:3,category:"Blocks"},
{name:"64x Dark Prismarine",price:4,category:"Blocks"},
{name:"64x End Stone",price:3,category:"Blocks"},
{name:"64x Purpur Block",price:4,category:"Blocks"},
{name:"64x Netherrack",price:2,category:"Blocks"},
{name:"64x Soul Sand",price:3,category:"Blocks"},
{name:"64x Soul Soil",price:3,category:"Blocks"},
{name:"64x Blackstone",price:3,category:"Blocks"},
{name:"64x Basalt",price:3,category:"Blocks"},
{name:"64x Magma Block",price:3,category:"Blocks"},
{name:"64x TNT",price:6,category:"Blocks"},
{name:"64x Sponge",price:7,category:"Blocks"},
{name:"64x Wet Sponge",price:7,category:"Blocks"},
{name:"64x Honey Block",price:4,category:"Blocks"},
{name:"64x Slime Block",price:4,category:"Blocks"},
{name:"64x Concrete",price:3,category:"Blocks"},
{name:"64x Concrete Powder",price:3,category:"Blocks"},
{name:"64x Terracotta",price:3,category:"Blocks"},
{name:"64x White Wool",price:2,category:"Blocks"},
{name:"64x Black Wool",price:2,category:"Blocks"},
{name:"64x Bookshelf",price:5,category:"Blocks"},
{name:"64x Moss Block",price:3,category:"Blocks"},
{name:"64x Clay",price:2,category:"Blocks"},
{name:"64x Snow Block",price:2,category:"Blocks"},



/* ================= WEAPONS ================= */
{name:"Wooden Sword",price:1,category:"Weapons"},
{name:"Stone Sword",price:2,category:"Weapons"},
{name:"Golden Sword",price:3,category:"Weapons"},
{name:"Iron Sword",price:4,category:"Weapons"},
{name:"Diamond Sword",price:5,category:"Weapons"},
{name:"Netherite Sword",price:7,category:"Weapons"},

{name:"Bow",price:3,category:"Weapons"},
{name:"Crossbow",price:5,category:"Weapons"},
{name:"Trident",price:8,category:"Weapons"},
{name:"Mace",price:10,category:"Weapons"},

{name:"Arrow",price:1,category:"Weapons"},
{name:"Spectral Arrow",price:2,category:"Weapons"},
{name:"Tipped Arrow",price:3,category:"Weapons"},
{name:"Shield",price:4,category:"Weapons"},

/* ================= ARMOR ================= */

{name:"Leather Helmet",price:2,category:"Armor"},
{name:"Leather Chestplate",price:3,category:"Armor"},
{name:"Leather Leggings",price:3,category:"Armor"},
{name:"Leather Boots",price:2,category:"Armor"},
{name:"Chainmail Helmet",price:3,category:"Armor"},
{name:"Chainmail Chestplate",price:4,category:"Armor"},
{name:"Chainmail Leggings",price:4,category:"Armor"},
{name:"Chainmail Boots",price:3,category:"Armor"},

{name:"Iron Helmet",price:4,category:"Armor"},
{name:"Iron Chestplate",price:5,category:"Armor"},
{name:"Iron Leggings",price:5,category:"Armor"},
{name:"Iron Boots",price:4,category:"Armor"},

{name:"Golden Helmet",price:4,category:"Armor"},
{name:"Golden Chestplate",price:5,category:"Armor"},
{name:"Golden Leggings",price:5,category:"Armor"},
{name:"Golden Boots",price:4,category:"Armor"},

{name:"Diamond Helmet",price:6,category:"Armor"},
{name:"Diamond Chestplate",price:7,category:"Armor"},
{name:"Diamond Leggings",price:7,category:"Armor"},
{name:"Diamond Boots",price:6,category:"Armor"},

{name:"Netherite Helmet",price:8,category:"Armor"},
{name:"Netherite Chestplate",price:10,category:"Armor"},
{name:"Netherite Leggings",price:10,category:"Armor"},
{name:"Netherite Boots",price:8,category:"Armor"},
/* ================= SPECIAL ITEMS ================= */

{name:"End Crystal",price:12,category:"Special"},
{name:"Wind Charge x64",price:8,category:"Special"},
{name:"Ender Pearl x16",price:6,category:"Special"},
{name:"Eye of Ender x16",price:8,category:"Special"},
{name:"Totem of Undying",price:15,category:"Special"},
{name:"Elytra",price:20,category:"Special"},
{name:"Dragon Egg",price:50,category:"Special"},
{name:"Nether Star",price:25,category:"Special"},
{name:"Beacon",price:30,category:"Special"},
{name:"Heart of the Sea",price:18,category:"Special"},
{name:"Conduit",price:22,category:"Special"},
{name:"Recovery Compass",price:12,category:"Special"},
{name:"Lodestone",price:18,category:"Special"},
{name:"Respawn Anchor",price:15,category:"Special"},
{name:"Enchanted Golden Apple",price:40,category:"Special"},
{name:"Golden Apple x16",price:12,category:"Special"},
{name:"Bottle o' Enchanting x64",price:10,category:"Special"},
{name:"Experience Bottle x64",price:10,category:"Special"},
{name:"Firework Rocket x64",price:6,category:"Special"},
{name:"Fire Charge x64",price:5,category:"Special"},
{name:"Blaze Rod x64",price:10,category:"Special"},
{name:"Ghast Tear x64",price:12,category:"Special"},
{name:"Phantom Membrane x64",price:10,category:"Special"},
{name:"Echo Shard x64",price:18,category:"Special"},
{name:"Disc Fragment x64",price:15,category:"Special"},
{name:"Heavy Core",price:40,category:"Special"},
{name:"Trial Key",price:20,category:"Special"},
{name:"Ominous Trial Key",price:30,category:"Special"},
{name:"Vault Key",price:25,category:"Special"},
{name:"Ominous Bottle",price:15,category:"Special"},
{name:"Sniffer Egg",price:20,category:"Special"},
{name:"Dragon Head",price:25,category:"Special"},
{name:"Mob Spawner",price:100,category:"Special"},
{name:"Command Block",price:250,category:"Special"},
{name:"Structure Block",price:200,category:"Special"},
{name:"Barrier x64",price:150,category:"Special"},
{name:"Light Block x64",price:150,category:"Special"},
{name:"Debug Stick",price:120,category:"Special"},
{name:"Jigsaw Block",price:200,category:"Special"},
{name:"Structure Void x64",price:180,category:"Special"},
/* ================= ENCHANTED BOOKS ================= */

{name:"Sharpness V Book",price:12,category:"Enchanted Books"},
{name:"Smite V Book",price:8,category:"Enchanted Books"},
{name:"Bane of Arthropods V Book",price:6,category:"Enchanted Books"},
{name:"Looting III Book",price:15,category:"Enchanted Books"},
{name:"Fire Aspect II Book",price:10,category:"Enchanted Books"},
{name:"Knockback II Book",price:8,category:"Enchanted Books"},
{name:"Sweeping Edge III Book",price:10,category:"Enchanted Books"},

{name:"Efficiency V Book",price:12,category:"Enchanted Books"},
{name:"Fortune III Book",price:18,category:"Enchanted Books"},
{name:"Silk Touch Book",price:20,category:"Enchanted Books"},
{name:"Unbreaking III Book",price:10,category:"Enchanted Books"},
{name:"Mending Book",price:25,category:"Enchanted Books"},

{name:"Protection IV Book",price:12,category:"Enchanted Books"},
{name:"Fire Protection IV Book",price:8,category:"Enchanted Books"},
{name:"Blast Protection IV Book",price:8,category:"Enchanted Books"},
{name:"Projectile Protection IV Book",price:8,category:"Enchanted Books"},
{name:"Feather Falling IV Book",price:10,category:"Enchanted Books"},
{name:"Depth Strider III Book",price:12,category:"Enchanted Books"},
{name:"Respiration III Book",price:10,category:"Enchanted Books"},
{name:"Aqua Affinity Book",price:8,category:"Enchanted Books"},
{name:"Thorns III Book",price:15,category:"Enchanted Books"},
{name:"Soul Speed III Book",price:18,category:"Enchanted Books"},
{name:"Swift Sneak III Book",price:20,category:"Enchanted Books"},

{name:"Power V Book",price:12,category:"Enchanted Books"},
{name:"Punch II Book",price:8,category:"Enchanted Books"},
{name:"Flame Book",price:10,category:"Enchanted Books"},
{name:"Infinity Book",price:20,category:"Enchanted Books"},

{name:"Quick Charge III Book",price:10,category:"Enchanted Books"},
{name:"Multishot Book",price:12,category:"Enchanted Books"},
{name:"Piercing IV Book",price:10,category:"Enchanted Books"},

{name:"Loyalty III Book",price:10,category:"Enchanted Books"},
{name:"Riptide III Book",price:15,category:"Enchanted Books"},
{name:"Channeling Book",price:15,category:"Enchanted Books"},
{name:"Impaling V Book",price:12,category:"Enchanted Books"},

{name:"Luck of the Sea III Book",price:10,category:"Enchanted Books"},
{name:"Lure III Book",price:8,category:"Enchanted Books"},

{name:"Frost Walker II Book",price:15,category:"Enchanted Books"},
{name:"Curse of Binding Book",price:5,category:"Enchanted Books"},
{name:"Curse of Vanishing Book",price:5,category:"Enchanted Books"},
{name:"Ranks",price:0,category:"Ranks"},
];
items.forEach(item => {
    item.stock = 99;
});

